repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.25.3
    hooks:
    -   id: pyproject-fmt

-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.31.1
    hooks:
    -   id: django-upgrade
        args: ["--target-version=4.2"]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
    -   id: ruff-check
        args: [ --fix ]
        # This files will be deleted soon, no need to spend time with lint-format fixes
        exclude: "setup.py|ez_setup.py"
    -   id: ruff-format

-   repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.27.0
    hooks:
    -   id: zizmor
        args: ["--no-progress", "--persona=auditor"]
