import os
import sys
from datetime import UTC, datetime
from pathlib import Path

import django

from drf_haystack import __version__

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, str(Path("..").resolve()))
os.environ["RUNTIME_ENV"] = "TESTSUITE"
os.environ["DJANGO_SETTINGS_MODULE"] = "tests.settings"

django.setup()


# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.extlinks",
    # TODO: Is this still needed?
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "drf_haystack"
copyright = f"{datetime.now(tz=UTC).date().year}, Rolf Håvard Blindheim"
author = "Rolf Håvard Blindheim"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The full version, including alpha/beta/rc tags.
version = release = __version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "drfhaystackdoc"

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/", None),
    "django": ("https://django.readthedocs.io/en/latest/", None),
    "haystack": ("https://django-haystack.readthedocs.io/en/latest/", None),
}

# Configurations for extlinks
extlinks = {
    "drf-pr": ("https://github.com/ulgens/drf-haystack/pull/%s", "PR#%s"),
    "drf-issue": ("https://github.com/ulgens/drf-haystack/issues/%s", "#%s"),
    "haystack-issue": ("https://github.com/django-haystack/django-haystack/issues/%s", "#%s"),
}
