name: "Tests"

on:
  push:
    branches:
      - main
  pull_request: ~

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.12.1

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}, Elasticsearch ${{ matrix.elastic-version
      }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        django-version:
          - "5.2.*"
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        elastic-version:
          - "7.17.29"
    env:
      UV_NO_DEV: 1
      ELASTICSEARCH_VERSION: ${{ matrix.elastic-version }}
      PYTHONUNBUFFERED: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv ${{ env.UV_VERSION }} & Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: ${{ env.UV_VERSION }}

      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gdal-bin

      - name: Start Elasticsearch
        run: docker compose up -d --quiet-pull --wait elasticsearch

      - name: Setup project and install dependencies
        run: uv sync

      # TODO: Remove this step, which relies on `setup.py`, once we
      # migrate the build backend to hatch with `pyproject.toml`
      - name: Install drf-haystack into the environment
        run: uv pip install .

      # Use always latest patch version of Django from the matrix version pattern `major.minor.*`.
      - name: Install matrix django
        env:
          DJANGO_VERSION: ${{ matrix.django-version }}
        run: uv pip install -U "django==${DJANGO_VERSION}"

      - name: Run tests
        run: uv run --no-sync manage.py test tests
