name: "Tests"

on:
  push:
    branches:
      - main
  pull_request: ~

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.12.1

jobs:
  run-tests:
    name: Test (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}, Elasticsearch ${{ matrix.elastic-version
      }}, DRF ${{ matrix.drf-version }})
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        django-version:
          - "5.2.*"
          - "6.0.*"
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        elastic-version:
          - "7.17.29"
        drf-version:
          - "3.16.*"
          - "3.17.*"
          - "3.18.*"
        exclude:
          # Django 6.0 support added in DRF 3.17.0
          # https://www.django-rest-framework.org/community/release-notes/#3170
          - drf-version: "3.16.*"
            django-version: "6.0.*"
          # Django 6.0 doesn't support Python 3.11
          # https://docs.djangoproject.com/en/6.0/faq/install/#what-python-version-can-i-use-with-django
          - django-version: "6.0.*"
            python-version: "3.11"

    env:
      UV_NO_DEV: 1
      ELASTICSEARCH_VERSION: ${{ matrix.elastic-version }}
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv ${{ env.UV_VERSION }} & Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: ${{ env.UV_VERSION }}

      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gdal-bin

      - name: Start Elasticsearch
        run: docker compose up -d --quiet-pull --wait elasticsearch

      - name: Setup project and install dependencies
        run: uv sync

      - name: Verify package builds
        run: uv build

      - name: Install matrix deps
        env:
          DJANGO_VERSION: ${{ matrix.django-version }}
          DRF_VERSION: ${{ matrix.drf-version }}
        run: uv pip install -U "django==${DJANGO_VERSION}" "djangorestframework==${DRF_VERSION}"

      - name: Run tests
        run: uv run --no-sync manage.py test tests
